version: '3'
services:
  web:
    build:
      context: .docker
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    network_mode: host
    depends_on:
      - sftp-server
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker-root-pass
      MYSQL_DATABASE: docker-db
      MYSQL_USER: docker-user
      MYSQL_PASSWORD: docker-pass
    volumes:
      - "./volumes/mysql:/var/lib/mysql:rw"
      - "./volumes/config/my.conf:/etc/mysql/conf.d/config-file.cnf"

  sftp-server:
    image: atmoz/sftp
    ports:
      - "2201:22"
    command: vanguard:vanguardpass:1001